### ISSUE TITLE
Virtual devices (_ct & _dimmer) dont show current status in Domoticz

### ISSUE THREAD

**Issue by TB404** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#836]
**Issue description**
Put general information here

**Additional information**
Zigbee2MQTT version: [1.28.2](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.28.2) commit: [e66fe85](https://github.com/Koenkk/zigbee2mqtt/commit/e66fe85)
Python version: 3.7
Domoticz version: 2022.2
Plugin version: latest git pull, v. 3.2.0-beta

I have created groups with both _dimmer and _ct to trigger the automatic creation of a “virtual device” in Domoticz.
The virtual device does show up.
Switching ON and OFF works.

What does not work: The device doesnt show the current state of the lights (dimm level and on/of state) and every time I trigger the device I get the below errors logs in Domoticz.

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs
`2022-11-16 16:38:03.426 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/groups_manager.py", line 73, in handle_mqtt_message
2022-11-16 16:38:03.426 Error: Zigbee: adapter.handle_mqtt_message(zigbee_message)
2022-11-16 16:38:03.426 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py", line 64, in handle_mqtt_message
2022-11-16 16:38:03.426 Error: Zigbee: device.handle_message(device_data, converted_message)
2022-11-16 16:38:03.426 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 193, in handle_message
2022-11-16 16:38:03.426 Error: Zigbee: }, **self.get_device_args(value, device, message))
2022-11-16 16:38:03.426 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/dimmer_switch.py", line 19, in get_device_args
2022-11-16 16:38:03.426 Error: Zigbee: return dict(args, Color=self.get_color_value(value, device), LastLevel=last_level)
2022-11-16 16:38:03.426 Error: Zigbee: AttributeError: 'DimmerSwitch' object has no attribute 'get_color_value'
2022-11-16 16:38:03.839 Error: Zigbee: Call to function 'onMessage' failed, exception details:
2022-11-16 16:38:03.841 Error: Zigbee: Traceback (most recent call last):
2022-11-16 16:38:03.841 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 299, in onMessage
2022-11-16 16:38:03.841 Error: Zigbee: _plugin.onMessage(Connection, Data)
2022-11-16 16:38:03.841 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 137, in onMessage
2022-11-16 16:38:03.841 Error: Zigbee: self.mqttClient.onMessage(Connection, Data)
2022-11-16 16:38:03.841 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 167, in onMessage
2022-11-16 16:38:03.841 Error: Zigbee: self.on_mqtt_message_cb(topic, message)
2022-11-16 16:38:03.841 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 213, in onMQTTPublish
2022-11-16 16:38:03.841 Error: Zigbee: self.groups_manager.handle_mqtt_message(topic, message)
2022-11-16 16:38:03.841 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/groups_manager.py", line 73, in handle_mqtt_message
2022-11-16 16:38:03.841 Error: Zigbee: adapter.handle_mqtt_message(zigbee_message)
2022-11-16 16:38:03.841 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py", line 64, in handle_mqtt_message
2022-11-16 16:38:03.841 Error: Zigbee: device.handle_message(device_data, converted_message)
2022-11-16 16:38:03.841 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 193, in handle_message
2022-11-16 16:38:03.842 Error: Zigbee: }, **self.get_device_args(value, device, message))
2022-11-16 16:38:03.842 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/dimmer_switch.py", line 19, in get_device_args
2022-11-16 16:38:03.842 Error: Zigbee: return dict(args, Color=self.get_color_value(value, device), LastLevel=last_level)
2022-11-16 16:38:03.842 Error: Zigbee: AttributeError: 'DimmerSwitch' object has no attribute 'get_color_value'
2022-11-16 16:38:05.247 Status: User: Admin (IP: 192.168.178.81) initiated a switch command (1519/Woonkamer Dimmer/Set Level)
2022-11-16 16:38:05.339 Error: Zigbee: Call to function 'onMessage' failed, exception details:
2022-11-16 16:38:05.342 Error: Zigbee: Traceback (most recent call last):
2022-11-16 16:38:05.342 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 299, in onMessage
2022-11-16 16:38:05.342 Error: Zigbee: _plugin.onMessage(Connection, Data)
2022-11-16 16:38:05.342 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 137, in onMessage
2022-11-16 16:38:05.342 Error: Zigbee: self.mqttClient.onMessage(Connection, Data)
2022-11-16 16:38:05.342 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 167, in onMessage
2022-11-16 16:38:05.342 Error: Zigbee: self.on_mqtt_message_cb(topic, message)
2022-11-16 16:38:05.342 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 213, in onMQTTPublish
2022-11-16 16:38:05.342 Error: Zigbee: self.groups_manager.handle_mqtt_message(topic, message)
2022-11-16 16:38:05.342 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/groups_manager.py", line 73, in handle_mqtt_message
2022-11-16 16:38:05.342 Error: Zigbee: adapter.handle_mqtt_message(zigbee_message)
2022-11-16 16:38:05.343 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py", line 64, in handle_mqtt_message
2022-11-16 16:38:05.343 Error: Zigbee: device.handle_message(device_data, converted_message)
2022-11-16 16:38:05.343 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 193, in handle_message
2022-11-16 16:38:05.343 Error: Zigbee: }, **self.get_device_args(value, device, message))
2022-11-16 16:38:05.343 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/dimmer_switch.py", line 19, in get_device_args
2022-11-16 16:38:05.343 Error: Zigbee: return dict(args, Color=self.get_color_value(value, device), LastLevel=last_level)
2022-11-16 16:38:05.343 Error: Zigbee: AttributeError: 'DimmerSwitch' object has no attribute 'get_color_value'
2022-11-16 16:38:05.721 Error: Zigbee: Call to function 'onMessage' failed, exception details:
2022-11-16 16:38:05.724 Error: Zigbee: Traceback (most recent call last):
2022-11-16 16:38:05.724 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 299, in onMessage
2022-11-16 16:38:05.724 Error: Zigbee: _plugin.onMessage(Connection, Data)
2022-11-16 16:38:05.724 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 137, in onMessage
2022-11-16 16:38:05.724 Error: Zigbee: self.mqttClient.onMessage(Connection, Data)
2022-11-16 16:38:05.724 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 167, in onMessage
2022-11-16 16:38:05.724 Error: Zigbee: self.on_mqtt_message_cb(topic, message)
2022-11-16 16:38:05.724 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 213, in onMQTTPublish
2022-11-16 16:38:05.725 Error: Zigbee: self.groups_manager.handle_mqtt_message(topic, message)
2022-11-16 16:38:05.725 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/groups_manager.py", line 73, in handle_mqtt_message
2022-11-16 16:38:05.725 Error: Zigbee: adapter.handle_mqtt_message(zigbee_message)
2022-11-16 16:38:05.725 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py", line 64, in handle_mqtt_message
2022-11-16 16:38:05.725 Error: Zigbee: device.handle_message(device_data, converted_message)
2022-11-16 16:38:05.725 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 193, in handle_message
2022-11-16 16:38:05.725 Error: Zigbee: }, **self.get_device_args(value, device, message))
2022-11-16 16:38:05.725 Error: Zigbee: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/dimmer_switch.py", line 19, in get_device_args
2022-11-16 16:38:05.725 Error: Zigbee: return dict(args, Color=self.get_color_value(value, device), LastLevel=last_level)
2022-11-16 16:38:05.725 Error: Zigbee: AttributeError: 'DimmerSwitch' object has no attribute 'get_color_value' `

**Comment by Anjerlaan** [comment]
I think I have the same issue #850
