### ISSUE TITLE
After Adding to zigbee2mqtt this device, TuYa IH012-RT01 , the plugin crash

### ISSUE THREAD

**Issue by acaonweb** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#847]
zigbee2mqtt recognise perfectly the device, plugin crashes
device link
https://www.zigbee2mqtt.io/devices/IH012-RT01.html#tuya-ih012-rt01

**Additional information**
Zigbee2MQTT version:
Zigbee2MQTT version
[1.28.4](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.28.4) commit: [52e545f9](https://github.com/Koenkk/zigbee2mqtt/commit/52e545f9)
Coordinator type
zStack3x0
Coordinator revision
20220219
Coordinator IEEE Address
0x00124b0021b95272
Frontend version
0.6.119
mosquitto version 2.0.13

Python version:
Python Version: 3.7.3

Domoticz version:
Version: 2022.2 (build **14880)**

Plugin version:
v. 3.2.0-beta

**Logs**
```
2022-12-26 12:16:26.558 Error: Zigbee2MQTT: Call to function 'onMessage' failed, exception details:
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: Traceback (most recent call last):
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 299, in onMessage
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: _plugin.onMessage(Connection, Data)
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 137, in onMessage
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: self.mqttClient.onMessage(Connection, Data)
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 167, in onMessage
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: self.on_mqtt_message_cb(topic, message)
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 166, in onMQTTPublish
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: self.devices_manager.set_devices(message)
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py", line 45, in set_devices
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: self.devices[device_adress] = UniversalAdapter(item)
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py", line 48, in __init__
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: self.register()
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py", line 33, in register
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: device.register(self._get_legacy_device_data())
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 142, in register
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: self._create_device(device_data)
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 78, in _create_device
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: device = self.create_device(unit, device_id, device_name)
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/selector_switch.py", line 30, in create_device
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: options['LevelNames'] = '|'.join(self.level_names)
2022-12-26 12:16:26.560 Error: Zigbee2MQTT: TypeError: sequence item 1: expected str instance, int found
2022-12-26 12:16:27.505 Zigbee2MQTT: Received available devices list from bridge
2022-12-26 12:16:27.484 Error: Zigbee2MQTT: Call to function 'onMessage' failed, exception details:
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: Traceback (most recent call last):
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 299, in onMessage
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: _plugin.onMessage(Connection, Data)
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 137, in onMessage
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: self.mqttClient.onMessage(Connection, Data)
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 167, in onMessage
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: self.on_mqtt_message_cb(topic, message)
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 166, in onMQTTPublish
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: self.devices_manager.set_devices(message)
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py", line 45, in set_devices
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: self.devices[device_adress] = UniversalAdapter(item)
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py", line 48, in __init__
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: self.register()
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py", line 33, in register
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: device.register(self._get_legacy_device_data())
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 142, in register
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: self._create_device(device_data)
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 78, in _create_device
2022-12-26 12:16:27.485 Error: Zigbee2MQTT: device = self.create_device(unit, device_id, device_name)
2022-12-26 12:16:27.486 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/selector_switch.py", line 30, in create_device
2022-12-26 12:16:27.486 Error: Zigbee2MQTT: options['LevelNames'] = '|'.join(self.level_names)
2022-12-26 12:16:27.486 Error: Zigbee2MQTT: TypeError: sequence item 1: expected str instance, int found
2022-12-26 12:16:28.403 Error: Zigbee2MQTT: Call to function 'onMessage' failed, exception details:
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: Traceback (most recent call last):
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 299, in onMessage
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: _plugin.onMessage(Connection, Data)
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 137, in onMessage
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: self.mqttClient.onMessage(Connection, Data)
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 167, in onMessage
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: self.on_mqtt_message_cb(topic, message)
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 166, in onMQTTPublish
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: self.devices_manager.set_devices(message)
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py", line 45, in set_devices
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: self.devices[device_adress] = UniversalAdapter(item)
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py", line 48, in __init__
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: self.register()
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py", line 33, in register
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: device.register(self._get_legacy_device_data())
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 142, in register
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: self._create_device(device_data)
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 78, in _create_device
2022-12-26 12:16:28.405 Error: Zigbee2MQTT: device = self.create_device(unit, device_id, device_name)
2022-12-26 12:16:28.406 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/selector_switch.py", line 30, in create_device
2022-12-26 12:16:28.406 Error: Zigbee2MQTT: options['LevelNames'] = '|'.join(self.level_names)
2022-12-26 12:16:28.406 Error: Zigbee2MQTT: TypeError: sequence item 1: expected str instance, int found
2022-12-26 12:16:29.096 Zigbee2MQTT: Received available devices list from bridge
2022-12-26 12:16:30.002 Error: Zigbee2MQTT: Call to function 'onMessage' failed, exception details:
2022-12-26 12:16:30.003 Error: Zigbee2MQTT: Traceback (most recent call last):
2022-12-26 12:16:30.003 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 299, in onMessage
2022-12-26 12:16:30.003 Error: Zigbee2MQTT: _plugin.onMessage(Connection, Data)
2022-12-26 12:16:30.003 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 137, in onMessage
2022-12-26 12:16:30.003 Error: Zigbee2MQTT: self.mqttClient.onMessage(Connection, Data)
2022-12-26 12:16:30.003 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 167, in onMessage
2022-12-26 12:16:30.003 Error: Zigbee2MQTT: self.on_mqtt_message_cb(topic, message)
2022-12-26 12:16:30.003 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 166, in onMQTTPublish
2022-12-26 12:16:30.003 Error: Zigbee2MQTT: self.devices_manager.set_devices(message)
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py", line 45, in set_devices
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: self.devices[device_adress] = UniversalAdapter(item)
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py", line 48, in __init__
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: self.register()
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py", line 33, in register
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: device.register(self._get_legacy_device_data())
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 142, in register
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: self._create_device(device_data)
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 78, in _create_device
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: device = self.create_device(unit, device_id, device_name)
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/selector_switch.py", line 30, in create_device
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: options['LevelNames'] = '|'.join(self.level_names)
2022-12-26 12:16:30.004 Error: Zigbee2MQTT: TypeError: sequence item 1: expected str instance, int found
```

**Comment by acaonweb** [comment]
@stas-demydiuk there something I can do more?

**Comment by acaonweb** [comment]
The problem is serious, because, after crash, if you add another device in zigbe2mqtt, the plugin stops to show devices exposed. the only way Is remove form zigbee2mtt the device that causes the crash. Adding again it some devices in domoticz don't respond properly... removing again from zigbee2mqtt everything start work again

**Comment by acaonweb** [comment]
to complete the issues, it seems that there any other users that have the problem and it seems it is related basically on motion sensors, 
https://www.domoticz.com/forum/viewtopic.php?p=296832#p296832

**Comment by stas-demydiuk** [comment]
Could you please update plugin and check if the error still persists

**Comment by acaonweb** [comment]
> Could you please update plugin and check if the error still persists

Hi, I've updated the plugin, added the device to domoticz. 
no crashes, and the device is correctly recognized and works
