### ISSUE TITLE
Returning log error after fresh install v.3.2.0-beta

### ISSUE THREAD

**Issue by Anjerlaan** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#850]
**Issue description**
Hi @stas-demydiuk ,
Yesterday have installed a fresh version of Domoticz (beta) and installed also a Domoticz-Zigbee2mqtt plugin with the plug-in manager. After adding the Zigbee2MQTT API Transport as a device, everything seems to work fine.
But I keep getting errors in the log as shown below.
This error repeats randomly except for the first 3 rows, that happens only once
Looks to me if the error is somewhere in "**dimmer_switch.py**"

What happens here?

**Additional information**
Zigbee2MQTT version: 1.28.4
Python version: 3.7.3
Domoticz version: 2022.2 (build 14905)
Plugin version: v.3.2.0-beta

**Logs**
```
2023-01-01 21:59:43.549 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/dimmer_switch.py", line 19, in get_device_args
2023-01-01 21:59:43.549 Error: Zigbee2MQTT: return dict(args, Color=self.get_color_value(value, device), LastLevel=last_level)
2023-01-01 21:59:43.549 Error: Zigbee2MQTT: AttributeError: 'DimmerSwitch' object has no attribute 'get_color_value'
2023-01-01 21:59:43.549 Error: Zigbee2MQTT:
2023-01-01 21:59:43.549 Error: Zigbee2MQTT: During handling of the above exception, another exception occurred:
2023-01-01 21:59:43.550 Error: Zigbee2MQTT:
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: Traceback (most recent call last):
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 299, in onMessage
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: _plugin.onMessage(Connection, Data)
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 137, in onMessage
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: self.mqttClient.onMessage(Connection, Data)
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 167, in onMessage
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: self.on_mqtt_message_cb(topic, message)
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 213, in onMQTTPublish
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: self.groups_manager.handle_mqtt_message(topic, message)
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/groups_manager.py", line 73, in handle_mqtt_message
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: adapter.handle_mqtt_message(zigbee_message)
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py", line 64, in handle_mqtt_message
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: device.handle_message(device_data, converted_message)
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 196, in handle_message
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: domoticz.error('Can\'t calculate the value for device ' + device.ID + ' from raw value "' + str(value) + '"')
2023-01-01 21:59:43.550 Error: Zigbee2MQTT: TypeError: can only concatenate str (not "int") to str
2023-01-01 22:12:32.783 Error: Zigbee2MQTT: Call to function 'onMessage' failed, exception details:
2023-01-01 22:12:32.785 Error: Zigbee2MQTT: Traceback (most recent call last):
2023-01-01 22:12:32.785 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 194, in handle_message
2023-01-01 22:12:32.785 Error: Zigbee2MQTT: }, **self.get_device_args(value, device, message))
2023-01-01 22:12:32.785 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/dimmer_switch.py", line 19, in get_device_args
2023-01-01 22:12:32.785 Error: Zigbee2MQTT: return dict(args, Color=self.get_color_value(value, device), LastLevel=last_level)
2023-01-01 22:12:32.785 Error: Zigbee2MQTT: AttributeError: 'DimmerSwitch' object has no attribute 'get_color_value'
```

**Comment by Anjerlaan** [comment]
Looks like the same issue as #836

**Comment by codalttjalling** [comment]
Got the same issue. Fixed it by fixing the string/int concat in the exception handler. 
Change line 196 in file /home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py  
Old:
`           domoticz.error('Can\'t calculate the value for device ' + device.ID + ' from raw value "' + str(value) + '"')
`
New:
`           domoticz.error('Can\'t calculate the value for device ' + str(device.ID) + ' from raw value "' + str(value) + '"')
`
