### ISSUE TITLE
light TS0505B appears in custom page but device not created in DZ

### ISSUE THREAD

**Issue by stan1m** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#853]
hello,

what is going well
![image](https://user-images.githubusercontent.com/123032358/213315248-825bbe1c-3a5c-485f-91fd-9b3ec7ba5d4f.png)

but many errors in log (explain why device is not created ?)
 2023-01-19 00:00:35.000 Error: Zigbee2MQTT: Call to function 'onMessage' failed, exception details:
2023-01-19 00:00:35.012 Error: Zigbee2MQTT: Traceback (most recent call last):
2023-01-19 00:00:35.012 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 287, in onMessage
2023-01-19 00:00:35.012 Error: Zigbee2MQTT: _plugin.onMessage(Connection, Data)
2023-01-19 00:00:35.012 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 137, in onMessage
2023-01-19 00:00:35.012 Error: Zigbee2MQTT: self.mqttClient.onMessage(Connection, Data)
2023-01-19 00:00:35.013 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 167, in onMessage
2023-01-19 00:00:35.013 Error: Zigbee2MQTT: self.on_mqtt_message_cb(topic, message)
2023-01-19 00:00:35.013 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 166, in onMQTTPublish
2023-01-19 00:00:35.013 Error: Zigbee2MQTT: self.devices_manager.set_devices(message)
2023-01-19 00:00:35.013 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py", line 44, in set_devices
2023-01-19 00:00:35.013 Error: Zigbee2MQTT: self.devices[device_id] = UniversalAdapter(item)
2023-01-19 00:00:35.013 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py", line 45, in __init__
2023-01-19 00:00:35.013 Error: Zigbee2MQTT: self.register()
2023-01-19 00:00:35.013 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py", line 33, in register
2023-01-19 00:00:35.014 Error: Zigbee2MQTT: device.register(self._get_legacy_device_data())
2023-01-19 00:00:35.014 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 81, in register
2023-01-19 00:00:35.014 Error: Zigbee2MQTT: self._create_device(device_data)
2023-01-19 00:00:35.014 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/device.py", line 47, in _create_device
2023-01-19 00:00:35.014 Error: Zigbee2MQTT: return self.create_device(unit, device_id, device_name)
2023-01-19 00:00:35.014 Error: Zigbee2MQTT: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/selector_switch.py", line 30, in create_device
2023-01-19 00:00:35.014 Error: Zigbee2MQTT: options['LevelNames'] = '|'.join(self.level_names)
2023-01-19 00:00:35.014 Error: Zigbee2MQTT: TypeError: sequence item 1: expected str instance, int found 

thanks for your help

![image](https://user-images.githubusercontent.com/123032358/213316059-45de1998-c793-4ab8-ace0-f016aa243cdf.png)

**Comment by stan1m** [comment]
full messages log when i disable/enable the plugin

 2023-01-19 00:18:50.500 Zigbee2MQTT: Worker thread started.
2023-01-19 00:18:50.499 Status: Zigbee2MQTT: Entering work loop.
2023-01-19 00:18:50.500 Status: Zigbee2MQTT: Started.
2023-01-19 00:18:51.299 Zigbee2MQTT: Debug logging mask set to: PYTHON
2023-01-19 00:18:51.299 Zigbee2MQTT: onStart called
2023-01-19 00:18:51.300 Zigbee2MQTT: Installing plugin custom page...
2023-01-19 00:18:51.300 Zigbee2MQTT: Copying files from /home/pi/domoticz/plugins/zigbee2mqtt/frontend to /home/pi/domoticz/www/templates
2023-01-19 00:18:51.348 Zigbee2MQTT: Installing plugin custom page completed.
2023-01-19 00:18:51.348 Zigbee2MQTT: MqttClient::__init__
2023-01-19 00:18:51.348 Zigbee2MQTT: MqttClient::open
2023-01-19 00:18:51.400 Zigbee2MQTT: onConnect called
2023-01-19 00:18:51.400 Zigbee2MQTT: Connected to MQTT Server: 127.0.0.1:1883
2023-01-19 00:18:51.400 Zigbee2MQTT: MQTT CLIENT ID: 'Domoticz_1674083931_2269'
2023-01-19 00:18:51.451 Zigbee2MQTT: MqttClient::subscribe
2023-01-19 00:18:51.454 Zigbee2MQTT: Subscribed to "zigbee2mqtt/#" topic
2023-01-19 00:18:51.456 Zigbee2MQTT: Zigbee2mqtt bridge is online
2023-01-19 00:18:51.456 Zigbee2MQTT: MqttClient::publish zigbee2mqtt/bridge/config/groups ()
2023-01-19 00:18:51.457 Zigbee2MQTT: Zigbee2mqtt log level is info
2023-01-19 00:18:51.457 Zigbee2MQTT: Joining new devices is disabled on the zigbee bridge
2023-01-19 00:18:51.467 Zigbee2MQTT: Received available devices list from bridge
2023-01-19 00:18:51.468 Zigbee2MQTT: Coordinator address is 0x00124b001936a1fa
2023-01-19 00:18:51.471 Zigbee2MQTT: Creating domoticz device to handle "keep_time" key for device with ieeeAddr 0xa4c1381f663f936a
2023-01-19 00:18:51.544 Zigbee2MQTT: Received groups list from bridge
2023-01-19 00:18:51.287 Status: Zigbee2MQTT: Initialized version 3.0.0

I have to use previous version because DZ fails at startup with last one
