### ISSUE TITLE
Switch on/off command doesn't work

### ISSUE THREAD

**Issue by DarkVillager** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#860]
**Issue description**
Put general information here
Can't seem to switch my switch on or off. It does work on the zigbee2mqtt frontend, just not in domoticz.

**Additional information**
Zigbee2MQTT version: 1.30.1
Version: 2022.1 (build 14575)
Build Hash: 4bb71ddff
Compile Date: 2022-10-18 07:36:30
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Oct 31 2022, 14:04:00) [GCC 8.3.0]
Plugin version: 3.1.0

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs:

2023-03-19 07:35:01.167 Error: zigbee2mqtt: Call to function 'onCommand' failed, exception details:
2023-03-19 07:35:01.168 Error: zigbee2mqtt: Traceback (most recent call last):
2023-03-19 07:35:01.168 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 303, in onCommand
2023-03-19 07:35:01.168 Error: zigbee2mqtt: _plugin.onCommand(DeviceId, Unit, Command, Level, Color)
2023-03-19 07:35:01.168 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 107, in onCommand
2023-03-19 07:35:01.168 Error: zigbee2mqtt: message = self.devices_manager.handle_command(device_id, unit, command, Level, Color)
2023-03-19 07:35:01.168 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py", line 74, in handle_command
2023-03-19 07:35:01.168 Error: zigbee2mqtt: return adapter.handle_command(alias, domoticz_device, command, level, color)
2023-03-19 07:35:01.168 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapter.py", line 413, in handle_command
2023-03-19 07:35:01.168 Error: zigbee2mqtt: device.handle_command(device_data, command, level, color)
2023-03-19 07:35:01.168 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices/switch/on_off_switch.py", line 39, in handle_command
2023-03-19 07:35:01.168 Error: zigbee2mqtt: domoticz.debug('Command "' + command + '" from device "' + device.Name + '"')
2023-03-19 07:35:01.168 Error: zigbee2mqtt: AttributeError: 'NoneType' object has no attribute 'Name'

**Comment by DarkVillager** [comment]
Seems to be happening due to a broken switch.
