### ISSUE TITLE
Xiaomi Aqara vibration sensor (DJT11LM)

### ISSUE THREAD

**Issue by DarkVillager** [stas-demydiuk/domoticz-zigbee2mqtt-plugin#868]
**Issue description**
Plugin doesn't expose "vibration" part of the sensor, even though it exists in zigbee2mqtt

**Additional information**
Zigbee2MQTT version: 1.31.2
Version: 2023.1 (build 15218)
Build Hash: 2d4900a44
Compile Date: 2023-04-29 15:01:10
dzVents Version: 3.1.8
Python Version: 3.7.3 (default, Jun 29 2023, 18:03:57) [GCC 8.3.0]
Plugin version: Newest release

**Logs**
Attach any additional logs here which might be useful: mqtt, domoticz, plugin logs
![image](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/assets/42322979/00714b6f-7c1c-4ca1-8e00-6c7490125ac0)
![image](https://github.com/stas-demydiuk/domoticz-zigbee2mqtt-plugin/assets/42322979/8387171a-dc21-4152-8113-2e4b7c5bceb9)

**Comment by stas-demydiuk** [comment]
Added the `vibration` feature support, could you please update the plugin and check

**Comment by DarkVillager** [comment]
I'll look in to this when I got time.

**Comment by DarkVillager** [comment]
```js
2023-12-23 17:08:03.461 Error: zigbee2mqtt: Call to function 'onMessage' failed, exception details:
2023-12-23 17:08:03.467 Error: zigbee2mqtt: Traceback (most recent call last):
2023-12-23 17:08:03.467 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 299, in onMessage
2023-12-23 17:08:03.468 Error: zigbee2mqtt: _plugin.onMessage(Connection, Data)
2023-12-23 17:08:03.468 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 137, in onMessage
2023-12-23 17:08:03.468 Error: zigbee2mqtt: self.mqttClient.onMessage(Connection, Data)
2023-12-23 17:08:03.468 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/mqtt.py", line 167, in onMessage
2023-12-23 17:08:03.468 Error: zigbee2mqtt: self.on_mqtt_message_cb(topic, message)
2023-12-23 17:08:03.468 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/plugin.py", line 215, in onMQTTPublish
2023-12-23 17:08:03.468 Error: zigbee2mqtt: self.devices_manager.handle_mqtt_message(topic, message)
2023-12-23 17:08:03.468 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/devices_manager.py", line 61, in handle_mqtt_message
2023-12-23 17:08:03.468 Error: zigbee2mqtt: adapter.handle_mqtt_message(zigbee_message)
2023-12-23 17:08:03.468 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/base_adapter.py", line 56, in handle_mqtt_message
2023-12-23 17:08:03.468 Error: zigbee2mqtt: converted_message = self.convert_message(message)
2023-12-23 17:08:03.468 Error: zigbee2mqtt: File "/home/pi/domoticz/plugins/zigbee2mqtt/adapters/lumi/DJT11LM.py", line 32, in convert_message
2023-12-23 17:08:03.468 Error: zigbee2mqtt: 'angle': message.raw['angle'],
2023-12-23 17:08:03.468 Error: zigbee2mqtt: KeyError: 'angle'```

**Comment by DarkVillager** [comment]
@stas-demydiuk ^ errors

**Comment by DarkVillager** [comment]
no
